apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "database-chart.fullname" . }}-creds
  labels:
    {{- include "database-chart.labels" . | nindent 4 }}
data:
  POSTGRES_USER: cm9vdA==
  POSTGRES_PASSWORD: cm9vdA==