kind: PersistentVolume
apiVersion: v1
metadata:
  name: {{ include "database-chart.fullname" . }}-pv
  labels:
    {{- include "database-chart.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: {{ .Values.pv.mountpath }}
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "database-chart.fullname" . }}-pvc
  labels:
    {{- include "database-chart.labels" . | nindent 4 }}
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi